import { forwardRef, useMemo } from 'react'
import { useStyleStore } from '../store/useStyleStore'
import { useUiStore } from '../store/useUiStore'
import { generateBlob } from '../generators/blob'
import { generateMesh } from '../generators/mesh'
import { generateGlass } from '../generators/glass'

// Real logical viewport sizes per device (width × height). Desktop is fluid width
// with a laptop-height frame; tablet/mobile use true portrait point dimensions.
const DEVICE_SIZE = {
  desktop: { width: '100%', height: '800px' }, // laptop viewport
  tablet: { width: '834px', height: '1194px' }, // iPad 11" portrait
  mobile: { width: '390px', height: '844px' }, // iPhone portrait
} as const

/** The live, exportable preview surface. PNG capture targets this node. */
const PreviewCanvas = forwardRef<HTMLDivElement>(function PreviewCanvas(_, ref) {
  const blob = useStyleStore((s) => s.blob)
  const mesh = useStyleStore((s) => s.mesh)
  const glass = useStyleStore((s) => s.glass)
  const { device, theme, bg, showCard } = useUiStore()

  const blobOut = useMemo(() => generateBlob(blob), [blob])
  const meshOut = useMemo(() => generateMesh(mesh), [mesh])
  const glassOut = useMemo(() => generateGlass(glass), [glass])

  const keyframes = [blobOut.keyframesCss, meshOut.keyframesCss].filter(Boolean).join('\n')

  return (
    <div className="flex h-full overflow-auto p-6">
      <div
        className="relative m-auto shrink-0 transition-[width,height] duration-300 ease-out"
        style={{ width: DEVICE_SIZE[device].width, height: DEVICE_SIZE[device].height, maxWidth: '100%' }}
      >
        <div
          ref={ref}
          className="relative h-full w-full overflow-hidden rounded-2xl ring-1 ring-black/20"
          style={{ background: bg === 'blob' ? blobOut.bgColor : '#0a0a12' }}
        >
          {keyframes && <style>{keyframes}</style>}

          {/* Background layer */}
          {bg === 'mesh' ? (
            <>
              {meshOut.svg && (
                <div
                  className="pointer-events-none absolute inset-0"
                  // SVG markup is generated by us from typed config — safe.
                  dangerouslySetInnerHTML={{ __html: meshOut.svg }}
                />
              )}
              <div style={meshOut.style} />
            </>
          ) : (
            blobOut.layers.map((l) => <div key={l.key} style={l.style} />)
          )}

          {/* Liquid-glass SVG filter (zero-size, must live in the DOM) */}
          {showCard && glassOut.svg && (
            <div dangerouslySetInnerHTML={{ __html: glassOut.svg }} />
          )}

          {/* Foreground: sample glass card + text/buttons */}
          {showCard && (
            <div className="relative z-10 flex h-full w-full items-center justify-center p-8">
              <div style={glassOut.style} className="flex flex-col justify-between">
                <div>
                    <p
                      className="text-[11px] font-semibold uppercase tracking-widest"
                      style={{ color: theme === 'light' ? '#1f2937aa' : '#ffffffaa' }}
                    >
                      {glass.mode === 'liquid' ? 'Liquid Glass' : 'Frosted Glass'}
                    </p>
                    <h2
                      className="mt-1 text-2xl font-semibold leading-tight"
                      style={{ color: theme === 'light' ? '#0f172a' : '#ffffff' }}
                    >
                      Design beautiful surfaces
                    </h2>
                  </div>
                  <div className="mt-4 flex gap-2">
                    <button
                      type="button"
                      className="rounded-lg px-3.5 py-2 text-sm font-medium"
                      style={{
                        background: theme === 'light' ? '#0f172a' : '#ffffff',
                        color: theme === 'light' ? '#ffffff' : '#0f172a',
                      }}
                    >
                      Get started
                    </button>
                    <button
                      type="button"
                      className="rounded-lg px-3.5 py-2 text-sm font-medium"
                      style={{
                        border: `1px solid ${theme === 'light' ? '#0f172a55' : '#ffffff55'}`,
                        color: theme === 'light' ? '#0f172a' : '#ffffff',
                      }}
                    >
                      Learn more
                    </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
})

export default PreviewCanvas
